### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jcupitt** [libvips/lua-vips#1]
Here's a TODO list of obvious problems that need fixing before we can declare 1.0. Please add more below.

- [x] check packaging: need to declare deps properly
- [x] need some docs
- [x] should we use `error()` for exceptions? what's the best way to do this?
- [x] need a test suite --- what's the best Lua unit test system?
- [x] need to use logging rather than print() --- what's the best logging framework?
- [x] need more gvalue types
- [x] need `new_from_buffer()`/`write_to_buffer()`
- [x] need `image:remove()` to remove metadata items
- [x] copy to memory, new memory etc.
- [x] not all binary operators know about arg reversal
- [x] need `new_from_array()` for matrix constants
- [x] look at setting and getting enums: can we use nicknames?
- [x] the rest of the operator overloads need implementing (we just have `+`)
- [x] add `__tostring` methods for image etc.
- [x] add more things to get standard fields from images, like `format`
- [x] add support for options in filenames
- [x] we assume that the input image is always the first required param, is this OK?
- [x] can we spot common errors like `a.add(b)` (ie. `.` instead of` :`) ?
- [x] need `object.get_typeof()` to test for fields
- [x] need hand-written wrappers for `bandjoin` etc.
- [x] use `..`, `[]`, `#` for band join, split and number
- [x] use `()` for get pixel
- [x] add enum expansions, like sin / cos / tan
- [x] add convenience functions like `bandsplit` etc
- [x] need auto-expanding constants
- [x] support MODIFY args
- [x] remove a lot of logging
- [x] leakcheck with a debug vips 
- [x] add to vips benchmark
- [x] make a benchmark against other Lua image processing libraries
- [x] upload the rockspec on 1.0!

**Comment by jcupitt** [comment]
Added simple logging. Off by default. Use `vips.log.enable(true)` to turn it on.

**Comment by jcupitt** [comment]
Now use `error()` for all errors.

**Comment by lexusburn** [comment]
Seems that something is wrong with operation.lua,
because i want to call write_to_buffer like this: buffer = image:write_to_buffer(„.jpg“)

It find the correct operation VipsForeignSaveJpegBuffer from write_to_buffer, but keeps the argument „.jpg“.
When it collects the arguments for operation, this argument isn’t needed anymore and it fails with the following error: „operation.lua:130: final argument is not a table“

Have a look on my fork: https://github.com/lexusburn/lua-vips

**Comment by jcupitt** [comment]
Oh dear, you're right. And gvalue will need some extra code to turn the buffer output into a Lua string as well. Hang on, I'll try fixing that.

**Comment by jcupitt** [comment]
OK, try again, I added `VipsBlob` support to gvalue.

I think the error you were seeing was because of the `format_string` parameter. You had:

```lua
        write_to_buffer = function(self, format_string, ...)
            local operation_name =
                ffi.string(vips.vips_foreign_find_save_buffer(format_string))
            if operation_name == nil then
                error(object.get_error())
            end
            return operation.call(ffi.string(operation_name),
                self, format_string, unpack{...})
        end,
```

But the `jpegsave_buffer` function just takes one required argument, the image to write to the buffer, you don't pass it the `format_string`. So `operation.lua` thought you were passing one argument too many, and that the extra argument wasn't a table of options. I'll try to improve the error message.

If you change it to be:

```lua
            return operation.call(ffi.string(operation_name),
                self, unpack{...})
```

I think it should work. 

I noticed a small bug: if you pass a crazy format string, like `".banana"`, then `vips_foreign_find_save_buffer()` will return `NULL`, and that will make `ffi.string()` crash. You need to do the conversion to string after testing for `nil`.

**Comment by lexusburn** [comment]
It works now to output a lua string. :-)

But i found a possible bug. I think it's not normal, that invert() doesn't work at huge images? 
I have a image with 2000x1500 pixels that ends in a broken image. Another smaller image works as expected.

load from buffer doesn't work at this time. I've  got segfaults if i call it. Had to investigate more...

**Comment by jcupitt** [comment]
Hey, well done!

Yes, it should be fine with huge images, though it will gobble memory. Are you setting the string length? If not, it'll search for a 0 terminator character, which obviously isn't right for images.

I've had to make huge changes to master, sorry :( You now need to add your code to `vips/Image_methods.lua`.

**Comment by jcupitt** [comment]
Do you have a preferred Lua unit tester? I've been looking at busted.

**Comment by lexusburn** [comment]
I don't have any preferred unit tester for lua, because i'm new in lua too. 
Had a look on busted and it looks good for me. :-)

Had called invert like this: `image4 = image4:invert()`
It works with a small png but not with a large. Will have a further look on it.

Changes are normally for such a work in progress. 
I will merge your changes into mine and try furthermore to implement buffer handling. :-)

**Comment by jcupitt** [comment]
Woo! We have a (small) test suite!

```
john@mm-jcupitt5 ~/GIT/lua-vips (master) $ busted .
●●●●●●●●●●●●●●
14 successes / 0 failures / 0 errors / 0 pending : 0.077788 seconds
```

**Comment by lexusburn** [comment]
\o/

**Comment by lexusburn** [comment]
added example for combine (extract, ifthenelse, insert). 
Load from buffer won't work. :(

**Comment by lexusburn** [comment]
write_to_buffer works in my fork. You can merge it into your code.

**Comment by jcupitt** [comment]
Great! I'll copy across.

Do you need an idea for another job? I was thinking of overloading `..` to mean bandjoin, and `[]` to mean band extract, so you could write:

```lua
image = image .. 255
```

and that would add an alpha channel, or:

```lua
image = image[2] .. image[1] .. image[3]
```

to swap R and G over. Those plus some tests would be great!

The other bindings use `()` to read a pixel (the `getpoint` operator), so you can write:

```
pixel = image(12, 2)
```

and `pixel` would be a table of the pixel values at that coordinate.

**Comment by jcupitt** [comment]
OK, merged everything from your fork. Good job!

**Comment by lexusburn** [comment]
> OK, merged everything from your fork. Good job!

Oh. Have in mind that load from buffer isn't working correctly. Only save to buffer works. 
Will have a look on concatination...

**Comment by jcupitt** [comment]
I think I've got write to buffer working!

```
john@kiwi:~/GIT/lua-vips (master)$ busted . 
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
67 successes / 0 failures / 0 errors / 0 pending : 0.242446 seconds
```

**Comment by jcupitt** [comment]
... and load from buffer.

**Comment by jcupitt** [comment]
Looks like we have some severe problems with reference counting, I think we need a global object table. I'll have a think.

**Comment by jcupitt** [comment]
OK, it's working! I fixed up your `combine.lua` example slightly and it now works beautifully:

```lua
local vips = require "vips"

-- uncomment for very chatty output
-- vips.log.enable(true)

local main = vips.Image.new_from_file("images/Gugg_coloured.jpg")
local sub = vips.Image.new_from_file("images/watermark.png")
local x, y, width, height = 100, 100, sub:width(), sub:height()

-- extract related area from main image
local extract = main:crop(x, y, width, height)

-- get rgb channels from watermark image
local rgb = sub:extract_band(0, {n = 3})

-- get alpha channel from watermark image
local mask = sub:extract_band(3)

-- use ifthenelse to combine extracted image with sub respecting the 
-- alpha channel
local composite = mask:ifthenelse(rgb, extract, {blend = true})

-- insert composite back in to main image on related area
local combined = main:insert(composite, x, y)

print("writing x.jpg ...")
combined:write_to_file("x.jpg")
```

Very fast, no leaks. You can run the test suite like this:

```
(cd spec; for i in *_spec.lua; do luajit $i; done)
```

You can't run via `busted`, unfortunately, because of some problems with `fork()` and luajit ffi. It seems to be a known problem. Anyway, it all passes reliably with no leaks. 

Woo!

**Comment by jcupitt** [comment]
I'll finish the tests next.

**Comment by jcupitt** [comment]
All done, and I added `..` and `()` overloads too.

I can't get the `[]` overload working, strange.

**Comment by jcupitt** [comment]
I think it's all done, I might stop there. I made a little benchmark against `magick`, the Lua ImageMagick binding:

https://github.com/jcupitt/lua-vips-bench

About 7.5x faster, 10x less memory \o/

**Comment by jcupitt** [comment]
I made a proper rock too, so you can now just install with 'luarocks install lua-vips`.

**Comment by jcupitt** [comment]
The page for the rock.

https://luarocks.org/modules/jcupitt/lua-vips

**Comment by jcupitt** [comment]
... and a blog post about it:

http://jcupitt.github.io/libvips/2017/06/01/libvips-for-Lua.html

**Comment by jcupitt** [comment]
All done! I'll annouce 1.0 in a day or two after some testing.
